#!/bin/bash
cat <<EOF
This is a S2I builder image for running a simple HTTP server. For
60 | Chapter 8: Understanding Source-to-Image Builders
instructions on using the S2I builder image see:
* https://github.com/openshift-katacoda/simple-http-server
EOF
